"""Add author

Revision ID: 7d053aab80ae
Revises: b3dfa7f94d42
Create Date: 2025-06-29 20:01:08.557100

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d053aab80ae'
down_revision = 'b3dfa7f94d42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coin_tweet_analysis', sa.Column('author', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('coin_tweet_analysis', 'author')
    # ### end Alembic commands ###
