"""Initial migration

Revision ID: 9590fa7492d4
Revises: 
Create Date: 2025-06-28 18:25:14.434486

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9590fa7492d4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coin_tweet_analysis',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('coin_name', sa.String(length=255), nullable=False),
    sa.Column('publish_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sentiment', sa.Enum('positive', 'negative', 'neutral', name='sentiment_enum'), nullable=False),
    sa.Column('keywords', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_coin_date', 'coin_tweet_analysis', ['coin_name', 'publish_date'], unique=False)
    op.create_index(op.f('ix_coin_tweet_analysis_coin_name'), 'coin_tweet_analysis', ['coin_name'], unique=False)
    op.create_index(op.f('ix_coin_tweet_analysis_id'), 'coin_tweet_analysis', ['id'], unique=False)
    op.create_index(op.f('ix_coin_tweet_analysis_publish_date'), 'coin_tweet_analysis', ['publish_date'], unique=False)
    op.create_index(op.f('ix_coin_tweet_analysis_sentiment'), 'coin_tweet_analysis', ['sentiment'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_coin_tweet_analysis_sentiment'), table_name='coin_tweet_analysis')
    op.drop_index(op.f('ix_coin_tweet_analysis_publish_date'), table_name='coin_tweet_analysis')
    op.drop_index(op.f('ix_coin_tweet_analysis_id'), table_name='coin_tweet_analysis')
    op.drop_index(op.f('ix_coin_tweet_analysis_coin_name'), table_name='coin_tweet_analysis')
    op.drop_index('ix_coin_date', table_name='coin_tweet_analysis')
    op.drop_table('coin_tweet_analysis')
    # ### end Alembic commands ###
