"""Add Trades

Revision ID: bae0d870deb5
Revises: 7d053aab80ae
Create Date: 2025-06-30 14:54:15.524968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bae0d870deb5'
down_revision = '7d053aab80ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trades',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('coin_name', sa.String(length=255), nullable=False),
    sa.Column('buy_price', sa.Float(), nullable=False),
    sa.Column('sell_price', sa.Float(), nullable=True),
    sa.Column('buy_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sell_date', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_trade_coin_date', 'trades', ['coin_name', 'buy_date'], unique=False)
    op.create_index(op.f('ix_trades_coin_name'), 'trades', ['coin_name'], unique=False)
    op.create_index(op.f('ix_trades_id'), 'trades', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trades_id'), table_name='trades')
    op.drop_index(op.f('ix_trades_coin_name'), table_name='trades')
    op.drop_index('ix_trade_coin_date', table_name='trades')
    op.drop_table('trades')
    # ### end Alembic commands ###
